Listen 8087

<VirtualHost *:8087>
    ServerName 10.0.151.101

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:5005/
    ProxyPassReverse / http://127.0.0.1:5005/

    ErrorLog /var/log/httpd/k8s-agent-tools-server-error.log
    CustomLog /var/log/httpd/k8s-agent-tools-server-access.log combined
</VirtualHost>
