import yaml
from datetime import date, timedelta, datetime
from pathlib import Path

from . import config
from .history_manager import list_snapshots, get_snapshot


def generate_daily(date_str, user='system'):
    snapshot = get_snapshot(date_str)
    if not snapshot:
        return None

    md = _render_daily(snapshot)

    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f'daily-{date_str}.md'
    path = config.REPORTS_DIR / filename
    with open(path, 'w') as f:
        f.write(md)
    return {'filename': filename, 'path': str(path), 'date': date_str}


def generate_weekly(year=None, week=None, user='system'):
    today = date.today()
    if year is None or week is None:
        year, week, _ = today.isocalendar()

    week_start = date.fromisocalendar(year, week, 1)
    dates = [(week_start + timedelta(days=i)).isoformat() for i in range(7)]
    snapshots = []
    for d in dates:
        snap = get_snapshot(d)
        if snap:
            snapshots.append(snap)

    if not snapshots:
        return None

    md = _render_weekly(year, week, dates, snapshots)

    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f'weekly-{year}-W{week:02d}.md'
    path = config.REPORTS_DIR / filename
    with open(path, 'w') as f:
        f.write(md)
    return {'filename': filename, 'path': str(path),
            'year': year, 'week': week, 'days_with_data': len(snapshots)}


def _render_daily(snap):
    d = snap.get('date', 'unknown')
    gen = snap.get('generated_at', '')
    by = snap.get('generated_by', 'system')
    execs = snap.get('executions', {})
    analyses = snap.get('analyses', {})
    integrations = snap.get('integrations', {})
    users = snap.get('users', {})

    total_e = execs.get('total', 0)
    completed = execs.get('completed', 0)
    failed = execs.get('failed', 0)
    pass_rate = f'{(completed / total_e * 100):.1f}%' if total_e > 0 else 'N/A'

    lines = [
        f'# K8s Agent Tools -- Daily Report {d}',
        '',
        f'Generated: {gen} by {by}',
        '',
        '---',
        '',
        '## Summary',
        '',
        '| Metric | Value |',
        '|---|---|',
        f'| Executions | {total_e} |',
        f'| Completed | {completed} |',
        f'| Failed | {failed} |',
        f'| Pass Rate | {pass_rate} |',
        f'| Analyses | {analyses.get("total", 0)} |',
        f'| Active Users | {users.get("active", 0)} |',
        '',
        '---',
        '',
    ]

    by_skill = execs.get('by_skill', {})
    if by_skill:
        lines.append('## Executions by Skill')
        lines.append('')
        lines.append('| Skill | Runs |')
        lines.append('|---|---|')
        for skill, count in sorted(by_skill.items(),
                                    key=lambda x: x[1], reverse=True):
            lines.append(f'| {skill} | {count} |')
        lines.append('')
        lines.append('---')
        lines.append('')

    by_type = analyses.get('by_type', {})
    findings = analyses.get('findings', {})
    if by_type:
        lines.append('## Analyses by Type')
        lines.append('')
        lines.append('| Type | Count |')
        lines.append('|---|---|')
        for atype, count in sorted(by_type.items()):
            lines.append(f'| {atype} | {count} |')
        lines.append('')
        lines.append(f'Findings: {findings.get("errors", 0)} errors, '
                     f'{findings.get("warnings", 0)} warnings, '
                     f'{findings.get("info", 0)} info')
        lines.append('')
        lines.append('---')
        lines.append('')

    if integrations:
        lines.append('## Integration Status')
        lines.append('')
        lines.append('| Source | Status | Count |')
        lines.append('|---|---|---|')
        for name, info in integrations.items():
            lines.append(f'| {name.title()} | {info.get("status", "?")} '
                         f'| {info.get("count", 0)} |')
        lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('*Generated by k8s-agent-tools-server Phase 6*')

    return '\n'.join(lines)


def _render_weekly(year, week, dates, snapshots):
    total_execs = sum(s.get('executions', {}).get('total', 0) for s in snapshots)
    total_completed = sum(s.get('executions', {}).get('completed', 0) for s in snapshots)
    total_failed = sum(s.get('executions', {}).get('failed', 0) for s in snapshots)
    total_analyses = sum(s.get('analyses', {}).get('total', 0) for s in snapshots)
    pass_rate = f'{(total_completed / total_execs * 100):.1f}%' if total_execs > 0 else 'N/A'

    skill_totals = {}
    for s in snapshots:
        for skill, count in s.get('executions', {}).get('by_skill', {}).items():
            skill_totals[skill] = skill_totals.get(skill, 0) + count

    lines = [
        f'# K8s Agent Tools -- Weekly Report {year}-W{week:02d}',
        '',
        f'Period: {dates[0]} to {dates[-1]}',
        f'Days with data: {len(snapshots)} / 7',
        '',
        '---',
        '',
        '## Week Summary',
        '',
        '| Metric | Value |',
        '|---|---|',
        f'| Total Executions | {total_execs} |',
        f'| Completed | {total_completed} |',
        f'| Failed | {total_failed} |',
        f'| Pass Rate | {pass_rate} |',
        f'| Total Analyses | {total_analyses} |',
        '',
        '---',
        '',
        '## Daily Breakdown',
        '',
    ]

    header = '| Day |'
    sep = '|---|'
    exec_row = '| Execs |'
    anal_row = '| Analyses |'
    for d in dates:
        short = d[-5:]
        snap = next((s for s in snapshots if s.get('date') == d), None)
        header += f' {short} |'
        sep += '---|'
        exec_row += f' {snap["executions"]["total"] if snap else "-"} |'
        anal_row += f' {snap["analyses"]["total"] if snap else "-"} |'

    lines.extend([header, sep, exec_row, anal_row, '', '---', ''])

    if skill_totals:
        lines.append('## Most Used Skills')
        lines.append('')
        lines.append('| Rank | Skill | Total Runs |')
        lines.append('|---|---|---|')
        for i, (skill, count) in enumerate(
                sorted(skill_totals.items(), key=lambda x: x[1], reverse=True), 1):
            lines.append(f'| {i} | {skill} | {count} |')
        lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('*Generated by k8s-agent-tools-server Phase 6*')

    return '\n'.join(lines)


def list_reports(limit=20):
    if not config.REPORTS_DIR.exists():
        return []
    items = []
    for f in config.REPORTS_DIR.iterdir():
        if f.suffix == '.md':
            stat = f.stat()
            rtype = 'weekly' if f.name.startswith('weekly') else 'daily'
            items.append({
                'filename': f.name,
                'type': rtype,
                'size': stat.st_size,
                'created_at': datetime.fromtimestamp(stat.st_mtime).isoformat(
                    timespec='seconds'),
            })
    items.sort(key=lambda x: x.get('created_at', ''), reverse=True)
    return items[:limit]


def get_report(filename):
    safe = Path(filename).name
    path = config.REPORTS_DIR / safe
    if not path.exists() or not path.suffix == '.md':
        return None
    return path.read_text()
